variables:
  TEST_VAR: "test variables"

rspec:
  stage: test
  script:
    - gem install bundler
    - bundle install
    - bundle exec rspec
    - mv coverage/coverage.xml coverage/cobertura-coverage.xml
    - echo "Testing variable $TEST_VAR"
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
