variables:
  TEST_VAR: "test variables"

stages:
  - install

install_node:
  stage: install
  image: node:latest
  script:
    - node --version
    - npm --version
    - echo "Testing variable $TEST_VAR"
  artifacts:
    paths:
      - node_version.txt
      - npm_version.txt
